### ISSUE TITLE
Different Unit file hash when running unit test

### ISSUE THREAD

**Issue by xianwen** [lyft/index-import#31]
When I run `tests/run.sh`, it fails with the following error:
```
➜ tests git:(master) ✗ ./run.sh
Testing clang indexes
expected.txt:2:8: error: CHECK: expected string not found in input
CHECK: Remapping file input/v5/units/input.c.o-7GYKMSFATPVS
       ^
<stdin>:2:1: note: scanning from here
Remapping file input/v5/units/input.c.o-UOY8CJSNVDTS
^
```

After investigating, I realized the hash of the Unit file generated is different from the expected value:
```
➜ tests git:(master) ✗ cd clang
➜ clang git:(master) ✗ xcrun clang -fsyntax-only -index-store-path input input.c
➜ clang git:(master) ✗ ll input/v5/units
total 8
-rw-r--r--  1 xianwen  staff   716B Sep 13 18:34 input.c.o-UOY8CJSNVDTS
```

Because the generated Unit file is named `input.c.o-UOY8CJSNVDTS`,  which is different from the expected `input/v5/units/input.c.o-7GYKMSFATPVS`, the test fails on my mac.

**Comment by xianwen** [comment]
FWIW, my local full path is `/Users/xianwen/src/index-import/tests/clang`, which is probably different from what the Unit test is expecting due to `/Users/xianwen/`

**Comment by kastiglione** [comment]
Thanks. This should be fixed by @ob's recent test fix.

**Comment by kastiglione** [comment]
#34 for reference.
