### ISSUE TITLE
Migrate from swift-clang to llvm-project

### ISSUE THREAD

**Issue by bigbangvn** [lyft/index-import#45]
This project (index-import) depends on swift-clang project (https://github.com/apple/swift-clang) which is frozen and only support  Swift <= 5.1.1
The latest Swift version is 5.2 (Xcode 11.4). So I guess we can have potential problem if using it with swift 5.2.
Is there any plan for migrating this?

**Comment by kastiglione** [comment]
Thanks for opening this issue!

I looked briefly at the Swift 5.2 branch before it was released and iirc there were no changes to the index data format.

However I do plan to update the to support Swift 5.2, there are some llvm API changes (FileManager deprecations) I know of as well that need to be fixed. I think I should be able to do these updates in the next week.

**Comment by bigbangvn** [comment]
I see, thanks @kastiglione

**Comment by kastiglione** [comment]
I forgot to update this issue. index-import now supports swift 5.2. Thanks again for reporting this.
